trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Docker@1
  inputs:
    containerRegistry: 'sc-acr-aspdotnetdemo-poc'
    repository: 'aspnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.SourceVersion)
